// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkpmckpmdqryfnxtzoms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcG1ja3BtZHFyeWZueHR6b21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTg4MjksImV4cCI6MjA2MTE3NDgyOX0.7thnhvp7PAf5pVTPH4dAwR5uDIFFxTqO3vgjQJEU30s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);